[build-system]
requires = [
  "setuptools",
  "opencv-python-headless"
]
build-backend = "setuptools.build_meta"

[project]
name = "opencv-python"
readme = "README.md"
description = "Force opencv-python-headless instead of opencv-python"
dynamic = ["version"]
license = "MIT"
license-files = ["LICENSE"]
authors = [
    {name = "Sandeep Nanda", email = "snanda85@gmail.com"},
]

dependencies = [
  "opencv-python-headless",
]

classifiers = [
  "Intended Audience :: Developers",

  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "https://github.com/snanda85/force-opencv-python-headless"
